# Monokai - termux.properties
# Install: ~/.termux/termux.properties

bell-character=ignore
terminal-margin-horizontal=4
terminal-margin-vertical=4

extra-keys = [['ESC','TAB','CTRL','ALT','-','|','UP','DOWN'],['FN','/',':','@','LEFT','RIGHT','PGUP','PGDN']]

allow-external-apps=true
terminal-cursor-blink-rate=0
terminal-cursor-style=block

hide-soft-keyboard-on-scroll=false
enforce-char-based-input=false
