# Dark Hacker - termux.properties
# Install: ~/.termux/termux.properties

# Bell
bell-character=ignore

# Terminal margin
terminal-margin-horizontal=4
terminal-margin-vertical=4

# Extra keys row
extra-keys = [['ESC','TAB','CTRL','ALT','-','|','UP','DOWN'],['FN','/',':','@','LEFT','RIGHT','PGUP','PGDN']]

# Allow external apps
allow-external-apps=true

# Cursor blink
terminal-cursor-blink-rate=600
terminal-cursor-style=block

# Soft keyboard
hide-soft-keyboard-on-scroll=false

# Enforce-char-based-input
enforce-char-based-input=false
